### ISSUE TITLE
Update-Migration некорректное расположение базы

### ISSUE THREAD

**Issue by melnyk-a** [melnyk-a/Cinema#10]
Почему, когда я вызываю Update Databese, база создается в LocalDb с заполнеными данными.

Но  если базу удалить и запустить код на выполнение, то она создается на сервере с незаполненными данными.

**Comment by truenorthpaul** [comment]
Это связано с `App.config` файлом. Когда запускается WPF-приложение, то используется его конфигурационный файл, в котором есть строка соединения для локального сервера с именем базы данных `Films`.

Когда вызывается команда `Update-Database`, компилируется и "запускается" только сборка с `DbContext`, т.е. `Cinema.Data.EntityFramework`. У нее есть свой конфигурационный файл, в котором нет строк соединения, а о конфигурационном файле WPF-приложения в данном контексте неизвестно, поэтому производится откат на настройки по умолчанию (место создания `LocalDB`).

В качестве решения, можно занести такую же строку соединения в конфигурационный файл сборки с Entity Framework.

Ну а на счет начальных данных, `Seed` метод вызывается только при `Update-Database`.
