### ISSUE TITLE
Ограничение not null для записи в таблице Actors 

### ISSUE THREAD

**Issue by melnyk-a** [melnyk-a/Cinema#9]
EntityFramework автоматически добавляет поле FilmCrewDto_Id и разрешает ему устанавливать значение null.

Создается оно от сюда:
 internal sealed class FilmCrewDto
    {
        [Required]
        public ICollection<ActorDto> ActorDtos { get; set; }
        //....
    }

![image](https://user-images.githubusercontent.com/35136814/47270915-3c0d5300-d57b-11e8-9042-8e6100f0bef9.png)

**Comment by truenorthpaul** [comment]
Не полностью понятно, какого эффекта хочется добиться. Необходимо, чтобы коллекция всегда была и была не пустая или, чтобы в коллекции нельзя было содержать `null`-значения?

Первый вариант можно почитать здесь: https://stackoverflow.com/questions/9218376/how-to-make-icollectionchild-entities-required-how

Второй вряд ли можно решить, пользуясь только атрибутами, но можно дописать такой код в свой `DbContext`:

```
protected override void OnModelCreating(DbModelBuilder modelBuilder)
{
    base.OnModelCreating(modelBuilder);

    modelBuilder
        .Entity<FilmCrewDto>()
        .HasMany(x => x.ActorDtos)
        .WithRequired()
        .WillCascadeOnDelete(false);
}
```
